# Generated by Django 4.1 on 2023-11-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('bus_price', models.IntegerField(default=None)),
                ('train_price', models.IntegerField(default=None)),
                ('flight_price', models.IntegerField(default=None)),
                ('main_image', models.ImageField(default=None, upload_to='')),
                ('image_a', models.ImageField(default=None, upload_to='')),
                ('image_b', models.ImageField(default=None, upload_to='')),
                ('image_c', models.ImageField(default=None, upload_to='')),
                ('food_price', models.IntegerField(default=None)),
                ('number_of_person', models.IntegerField(default=None)),
                ('days', models.IntegerField(default=None)),
                ('nights', models.IntegerField(default=None)),
                ('description', models.TextField(default=None)),
            ],
        ),
    ]
