# Generated by Django 2.2 on 2023-12-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20231203_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmodel',
            name='days',
        ),
        migrations.RemoveField(
            model_name='destinationmodel',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='destinationmodel',
            name='number_of_person',
        ),
    ]
