# Generated by Django 2.2 on 2023-12-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20231205_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blog',
            new_name='blog_name',
        ),
    ]
