# Generated by Django 2.2 on 2023-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20231206_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
