# Generated by Django 2.2 on 2023-12-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_registerationmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationmodel',
            name='address',
        ),
    ]
