# Generated by Django 2.2 on 2023-12-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_continentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='continent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.ContinentModel'),
        ),
    ]
