# Generated by Django 2.2 on 2023-12-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_destinationmodel_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmodel',
            name='continent',
        ),
    ]
