# Generated by Django 2.2 on 2023-12-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_destinationmodel_continent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
