# Generated by Django 4.1 on 2023-12-11 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0016_registerationmodel_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_detail', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.destinationmodel')),
                ('all_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
