# Generated by Django 4.1 on 2023-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_usertablemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertablemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
