# Generated by Django 4.1 on 2023-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_alter_usertablemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='bus_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='flight_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='food_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='train_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
