# Generated by Django 4.1 on 2023-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_destinationmodel_bus_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='bus_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='flight_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='food_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='train_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
