# Generated by Django 2.2 on 2023-12-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_remove_destinationmodel_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmodel',
            name='number_of_person',
        ),
    ]
