# Generated by Django 2.2 on 2023-12-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_remove_destinationmodel_number_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='number_of_person',
            field=models.IntegerField(default=None),
        ),
    ]
