# Generated by Django 2.2 on 2023-12-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_bookingmodel_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='register',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.RegisterationModel'),
        ),
    ]
