# Generated by Django 2.2 on 2023-12-18 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_bookingmodel_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='register',
        ),
    ]
