# Generated by Django 2.2 on 2023-12-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_bookingmodel_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingModel',
        ),
    ]
