# Generated by Django 2.2 on 2023-12-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_auto_20231219_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default=None)),
                ('detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.RegisterationModel')),
            ],
        ),
    ]
