# Generated by Django 2.2 on 2023-12-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_feedbackmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='detail',
            new_name='fb_detail',
        ),
    ]
