# Generated by Django 2.2 on 2023-12-21 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0036_auto_20231220_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='fbdetail',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
