# Generated by Django 2.2 on 2023-12-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0038_remove_bookingmodel_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='destinationmodel',
            name='number_of_person',
        ),
    ]
