# Generated by Django 2.2 on 2023-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0039_auto_20231222_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='night',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='number_of_person',
            field=models.BigIntegerField(default=None),
        ),
    ]
