# Generated by Django 2.2 on 2023-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0040_auto_20231222_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='adult_per_day',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='destinationmodel',
            name='child_per_day',
            field=models.IntegerField(default=10000),
        ),
    ]
