# Generated by Django 2.2 on 2023-12-26 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0047_remove_destinationmodel_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
