# Generated by Django 2.2 on 2023-12-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0050_remove_feedbackmodel_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travel.RegisterationModel'),
        ),
    ]
