# Generated by Django 2.2 on 2023-12-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0053_feedbackmodel_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='detail',
        ),
    ]
