# Generated by Django 2.2 on 2023-12-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0055_feedbackmodel_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='detail',
            new_name='register',
        ),
    ]
