# Generated by Django 2.2 on 2023-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0056_auto_20231227_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
